---
- include_vars: "{{ ansible_os_family }}.yml"

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: conf.yml

- include: haproxy.yml
  when: haproxy_script_location != ""

- name: Delete old slave info to ensure clean startup of Chronos after an upgrade
  file: path=/tmp/mesos/meta/slaves/latest state=absent

- name: Start Chronos service
  service: name=chronos state=restarted enabled=yes
